export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000/api/v1";

export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    me: "/auth/me",
    refresh: "/auth/refresh",
  },
  products: {
    list: "/products/list",
    featured: "/products/featured",
    trending: "/products/trending",
    recent: "/products/recent",
    seasonal: "/products/seasonal",
    giTagged: "/products/gi-tagged",
    get: "/products/get",
    search: "/products/list",
  },
  categories: "/categories",
  nutrition: "/nutrition",
  locations: "/locations",
  cart: "/cart",
  wishlist: "/wishlist",
  orders: "/orders",
  notifications: "/notifications",
  buyer: {
    dashboard: "/buyer/dashboard",
    profile: "/buyer/profile",
    orders: "/buyer/orders",
    orderDetail: (id: string) => `/buyer/orders/${id}`,
  },
  seller: {
    dashboard: "/seller/dashboard",
    products: "/seller/products",
    product: (id: string) => `/seller/products/${id}`,
    inventory: "/seller/inventory",
    orders: "/seller/orders",
    analytics: "/seller/analytics",
    customers: "/seller/customers",
    profile: "/seller/profile",
  },
  admin: {
    dashboard: "/admin/dashboard",
    sellers: "/admin/sellers",
    approveSeller: (id: string) => `/admin/sellers/${id}/approve`,
    rejectSeller: (id: string) => `/admin/sellers/${id}/reject`,
    buyers: "/admin/buyers",
    products: "/admin/products",
    approveProduct: (id: string) => `/admin/products/${id}/approve`,
    rejectProduct: (id: string) => `/admin/products/${id}/reject`,
    categories: "/admin/categories",
    seasonCalendar: "/admin/season-calendar",
    nutrition: "/admin/nutrition",
    giTags: "/admin/gi-tags",
    locations: "/admin/locations",
    orders: "/admin/orders",
    reports: "/admin/reports",
  },
} as const;
